### ISSUE TITLE
Seeking help with the loss curve

### ISSUE THREAD

**Issue by 311dada** [princeton-nlp/CEPE#2]
Congratulations on your excellent work. Intuitively, introducing new parameters for cross-attention may lead to a high loss. Could you please share your loss curve? Thanks a lot!

**Comment by howard-yen** [comment]
Hi, apologies for the late reply.
You can check this [wandb link](https://api.wandb.ai/links/howard-yen/lwwfkxjh) for the evaluation loss curve during training.
Your intuition is correct --- we also found that simply introducing new parameters in the form of cross-attention results in higher loss and training instability. Therefore, we use carefully weight initialization using the self-attention weights, and also the warmup stage (described in section 2.3 and appendix A.2 in the paper).

Although I do not have the loss curves for the warmup training stage plotted on wandb, it looks quite similar to the one linked. The main difference is that the loss starts up higher, but due to the easy learning objective, the loss quickly converges to near 0 after just a couple thousands of steps.
Please let me know if you have any other questions!

**Comment by 311dada** [comment]
Thanks a lot!
